framework:
  website: armeria.dev
  version: 1.37

  build:
    - mvn package

  files:
    - target/benchmark.jar

  binaries:
    - target/benchmark.jar

language:
  engines:
    default:
      command: /usr/bin/java -jar /opt/web/target/benchmark.jar
