framework:
  website: hyperf.io
  version: 3.1

  engines:
    - swoole

  extensions:
    - redis

  modules:
    - pcntl

  bootstrap:
    - curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --prefer-dist --classmap-authoritative
    - composer dumpautoload -o
    - echo "swoole.use_shortname = 'Off'" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
    - php sbin/hyperf.php
language:
  engines:
    swoole:
      command: php sbin/hyperf.php start
