framework:
  website: patx.gitman.io/micropie
  github: patx/micropie
  version: "0.30"

  engines:
    - granian
    - uvicorn
    - hypercorn
    - daphne
    - gunicorn

language:
  engines:
    gunicorn:
      environment:
        WORKER_CLASS: asgi
