[tools]
ruby = "latest"
php = "latest"
python = "latest"
deno = "latest"
java = "latest"
scala = "2"
kotlin = "latest"
node = "latest"
clojure = "latest"
bun = "latest"
dotnet = "latest"
crystal = "1.21"

[settings]
auto_install = false
