framework:
  website: nextjs.org
  github: vercel/next.js
  version: 16.3

  files:
    - app
    - app.mjs
    - cluster.mjs
    - package.json

  bootstrap:
    - NEXT_TELEMETRY_DISABLED=1 npm run build
