framework:
  website: undertow.io
  version: 2.4

  build:
    - mvn package

  files:
    - target/server-jar-with-dependencies.jar

  binaries:
    - target/server-jar-with-dependencies.jar

language:
  engines:
    default:
      command: /usr/bin/java -jar /opt/web/target/server-jar-with-dependencies.jar
