framework:
  website: hleb2framework.ru
  github: phphleb/hleb
  version: 2.0

  engines:
    - swoole

  files:
    - console

  bootstrap:
    - curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --prefer-dist --classmap-authoritative
    - composer dumpautoload -o
    - php console --generate-key
    - php console --routes-upd

language:
  engines:
    swoole:
      command: php public/index.php
