framework:
  website: activej.io
  version: 5.5

  build:
    - mvn clean package

  binaries:
    - target/benchmark.jar

language:
  engines:
    default:
      command: /usr/bin/java -jar target/benchmark.jar benchmark.App
