language:
  version: 1.15
  website: gleam.run

  files:
    - gleam.toml
    - "**/*.gleam"

  engines:
    default:
      command: /app/entrypoint.sh
      options: run

framework:
  engines:
    - default
