framework:
  website: symfony.com
  version: 8.1

  files:
    - bin/console
    - config/**/*.yaml
    - .env.local.php

  bootstrap:
    - curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --prefer-dist --classmap-authoritative
    - composer dumpautoload -o
    - mkdir -p var/log && chown www-data var/log
    - mkdir -p var/cache && chown www-data var/cache
    - php bin/console cache:warmup --no-debug
