framework:
  website: leafo.net/lapis/
  version: 1.18

  image: openresty/openresty:alpine-fat

  build_deps:
    - openssl-dev

  build:
    - /usr/local/openresty/luajit/bin/luarocks install lapis
    - lapis new

language:
  engines:
    default:
      command: lapis server production
