requires 'Dancer2', '> 0.400001';
# Gazelle or Starman
requires 'Gazelle';

# XS speed-ups
requires 'Class::XSAccessor';
requires 'Crypt::URandom';
requires 'HTTP::XSHeaders';
requires 'Math::Random::ISAAC::XS';
requires 'MooX::TypeTiny';
requires 'Scope::Upper';
requires 'Type::Tiny::XS';
requires 'URL::Encode::XS';
