language:
  version: 26
  compiler: maven

  files:
    - src/**/*.java
    - pom.xml
    - src/**/*.xml
    - src/**/*.yml
    - src/**/*.jsp
    - '**/*.kts'
    - '**/*.properties'

  engines:
    default: {}
    graalvm:
      graalvm: true

framework:
  command: /usr/bin/java -jar /opt/web/target/benchmark-1.0.0.jar
  engines:
    - default
    - graalvm
