server.port=3000
server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.mvc.problemdetails.enabled=true
spring.threads.virtual.enabled=true
spring.servlet.multipart.max-file-size=64KB
spring.servlet.multipart.max-request-size=64KB
spring.servlet.multipart.file-size-threshold=64KB
