framework:
  github: pedestal/pedestal
  version: "0.6"

  build:
    - lein uberjar

  binaries:
    - target/the-benchmarker-pedestal-0.0.1-SNAPSHOT-standalone.jar

language:
  compiler: lein
  java: 21
  engines:
    default:
      command: java -Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+DisableExplicitGC -Dpedestal.env=production -Dclojure.compiler.direct-linking=true -jar target/the-benchmarker-pedestal-0.0.1-SNAPSHOT-standalone.jar
