framework:
  website: aspectran.com
  github: aspectran/aspectran
  version: 9.6.5

  build:
    - mvn clean package

  files:
    - config/**/*

  static_files:
    - config/**/*

  binaries:
    - target/benchmark-jar-with-dependencies.jar

language:
  engines:
    default:
      command: /usr/bin/java -Daspectran.profiles.active=benchmark -jar /opt/web/target/benchmark-jar-with-dependencies.jar /opt/web /config/aspectran-config.apon
