framework:
  website: rubyonrails.org
  version: 8.1.4

  bootstrap:
    - mkdir -p tmp/pids

  build_deps:
    - libsqlite3-dev
    - libyaml-dev
    - pkg-config

  environment:
    RAILS_ENV: production
    SECRET_KEY_BASE_DUMMY: "1"
    RUBY_YJIT_ENABLE: 0
