framework:
  website: helidon.io
  version: 27

  build:
    - mvn clean package

  binaries:
    - target/classes
    - target/libs

  command: /usr/bin/java -cp '/opt/web/target/classes:/opt/web/target/libs/*' web.helidon.Main

  engines:
    - default

language:
  version: 27
