framework:
  website: luminusweb.com
  version: 4.52

  files:
    - "**/*.clj"
    - "**/*.edn"
    - "**/*.xml"
    - "**/*.html"

  build:
    - lein uberjar

  binaries:
    - target/uberjar/luminus.jar

language:
  compiler: lein
  java: 21
  engines:
    default:
      command: java -jar target/uberjar/luminus.jar 3000
