framework:
  website: luminusweb.com
  version: 4.52

  files:
    - "**/*.clj"
    - "**/*.edn"
    - "**/*.xml"
    - "**/*.html"

  build:
    - lein uberjar

  binaries:
    - target/uberjar/luminus.jar

language:
  compiler: lein
  java: 21
  engines:
    default:
      command: java -Xms512m -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+DisableExplicitGC -Dconf=prod-config.edn -Dluminus.env=production -jar target/uberjar/luminus.jar 3000
