framework:
  website: expressjs.com
  version: 5.2

  build:
    - npm install --production

  binaries:
    - node app.mjs

language:
  engines:
    default:
      command: /usr/bin/node /opt/web/app.mjs
      environment:
        - NODE_ENV=production
        - NODE_OPTIONS=--max-old-space-size=2048
        - LOG_LEVEL=warn
