[package]
name = "zeno-rs-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
zenocore = "0.2.3"
zenoengine = "0.2.3"
zeno-std = "0.2.3"
matchit = "0.8"
axum = { version = "0.8", default-features = false, features = ["tokio", "http1"] }
tokio = { version = "1.40", features = ["rt-multi-thread", "net", "macros"] }
