framework:
  github: supranim/supranim
  version: 0.1
  build_opts:
    - "--mm:atomicArc"
    - "-d:webapp"
    - "-d:httpbench"
    - "-d:features.emitter.powpow"

  build_deps:
    - libssl-dev

  runtime_deps:
    - libssl3
