framework:
  website: javalin.io
  version: 7.2

  build:
    - mvn clean compile assembly:single -DskipTests

  binaries:
    - target/benchmark-jar-with-dependencies.jar

language:
  engines:
    default:
      command: /usr/bin/java -jar /opt/web/target/benchmark-jar-with-dependencies.jar
      environment:
        - LOG_LEVEL=WARN
