language:
  version: 1.21
  files:
    - "**/*.cr"
    - shard.yml
  environment:
    CRYSTAL_WORKERS: $(nproc)
  engines:
    default:
      command: /app/bin/server

framework:
  engines:
    - default
