framework:
  website: vertx.io/docs/vertx-core/java/
  version: 5.1

  build:
    - mvn clean package -DskipTests

  files:
    - target/benchmark.jar

  binaries:
    - target/benchmark.jar

language:
  engines:
    default:
      command: /usr/bin/java -jar /opt/web/target/benchmark.jar -instances $(nproc)
      environment:
        - LOG_LEVEL=WARN
        - CONSOLE_LOGGING=false
