framework:
  website: nestjs.com
  version: 11.1

  files:
    - nest-cli.json
    - src/**.ts
    - tsconfig.build.json
    - tsconfig.json
    - package.json
    - cluster.mjs

  bootstrap:
    - npm -g install @nestjs/cli
    - npm install --production
    - nest build

  binaries:
    - cluster.mjs
    - dist/app.js

language:
  engines:
    node:
      command: node cluster.mjs
      environment:
        - NODE_ENV=production
        - NODE_OPTIONS=--max-old-space-size=2048
        - NODE_APP=dist/app.js
