language:
  version: 1.27

  engines:
    net-http:
      command: /go/bin/app
    fasthttp:
      command: /go/bin/app
    gogo:
      command: /go/bin/app
    gnet:
      command: /go/bin/app

framework:
  engines:
    - net-http

  files:
    - "**/*.go"
    - go.mod
