<?php

return [
    'debug' => false,
    'log.enabled' => true,
    'max.log.level' => 'info',
    'max.cli.log.level' => 'info',
    'log.level.in-cli' => false,
    'error.reporting' => E_ALL,
    'log.sort' => true,
    'log.stream' => false,
    'log.format' => 'row',
    'log.db.excess' => 0,
    'timezone' => 'UTC',
    'routes.auto-update' => false,
    'container.mock.allowed' => false,
    'app.cache.on' => false,
    'twig.options' => [
        'debug' => true,
        'charset' => 'utf-8',
        'auto_reload' => true,
        'strict_variables' => false,
        'autoescape' => false,
        'optimizations' => -1,
        'cache' => true,
    ],
    'twig.cache.inverted' => [],
    'show.request.id' => false,
    'max.log.size' => 0,
    'max.cache.size' => 0,
];
