done = function(summary, latency, requests)
   io.write("{\n")
   io.write(string.format("    \"latency.min\": %d,\n", latency.min))
   io.write(string.format("    \"latency.max\": %d,\n", latency.max))
   io.write(string.format("    \"latency.mean\": %d,\n", latency.mean))
   io.write(string.format("    \"latency.stdev\": %d,\n", latency.stdev))
   io.write(string.format("    \"requests\": %d,\n", summary.requests))
   io.write(string.format("    \"bytes\": %d,\n", summary.bytes))
   io.write(string.format("    \"duration\": %d,\n", summary.duration))
   io.write(string.format("    \"errors.connect\": %d,\n", summary.errors.connect))
   io.write(string.format("    \"errors.read\": %d,\n", summary.errors.read))
   io.write(string.format("    \"errors.write\": %d,\n", summary.errors.write))
   io.write(string.format("    \"errors.status\": %d,\n", summary.errors.status))
   io.write(string.format("    \"errors.timeout\": %d,\n", summary.errors.timeout))
   io.write("},\n")
end