done = function(summary, latency, requests)
   io.write("$")
   io.write("{\n")
                 io.write("    \"latency\": {\n")
   io.write(string.format("        \"min\": %d,\n", latency.min))
   io.write(string.format("        \"max\": %d,\n", latency.max))
   io.write(string.format("        \"mean\": %d,\n", latency.mean))
   io.write(string.format("        \"stdev\": %d\n", latency.stdev))
                 io.write("    },\n")
   io.write(string.format("    \"requests\": %d,\n", summary.requests))
   io.write(string.format("    \"bytes\": %d,\n", summary.bytes))
   io.write(string.format("    \"duration\": %d,\n", summary.duration))
                 io.write("    \"errors\": {\n")
   io.write(string.format("        \"connect\": %d,\n", summary.errors.connect))
   io.write(string.format("        \"read\": %d,\n", summary.errors.read))
   io.write(string.format("        \"write\": %d,\n", summary.errors.write))
   io.write(string.format("        \"status\": %d,\n", summary.errors.status))
   io.write(string.format("        \"timeout\": %d\n", summary.errors.timeout))
                 io.write("    }\n")
   io.write("}\n")
end