language:
  version: 8.5

  files:
    - "**/*.php"
    - composer.json

  before_build:
    - curl -fL --output /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar && install /tmp/pie /usr/local/bin

  bootstrap:
    - curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --prefer-dist --classmap-authoritative
    - composer dumpautoload -o

  engines:
    php-fpm:
      deps:
        - nginx
    workerman:
      before_build:
        - docker-php-ext-install pcntl sockets
      extensions:
        - osmanov/pecl-event
      deps:
        - libevent-dev
        - libssl-dev
      command: php public/index.php start
    road-runner:
      extensions:
        - extport/protobuf
      files:
        - .rr.yaml
      bootstrap:
        - vendor/bin/rr get-binary
      modules:
        - sockets
      command: ./rr serve
    swoole:
      before_build:
        - curl -fL --output /usr/local/bin/pie https://github.com/php/pie/releases/latest/download/pie.phar && chmod +x /usr/local/bin/pie && pie install --no-cache swoole/swoole:6.2.2
      command: php public/index.php
      build_deps:
        - libbrotli-dev
        - libssl-dev
    reactphp:
      extensions:
        - osmanov/pecl-event
      deps:
        - libevent-dev
        - libicu-dev
        - libssl-dev

framework:
  engines:
    - php-fpm
