;default in PHP 8.5
;opcache.enable=1
;opcache.enable_cli=1

opcache.memory_consumption=512
opcache.interned_strings_buffer=64
opcache.max_accelerated_sources=32531
opcache.validate_timestamps=0
opcache.save_comments=0

opcache.jit=tracing
opcache.jit_buffer_size=256M
