framework:
  github: fomo-framework/fomo
  version: 2.4

  files:
    - "**/*.php"
    - composer.json
    - engineer

  engines:
    - swoole

  extensions:
    - redis

  modules:
    - pcntl

  bootstrap:
    - curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --prefer-dist --classmap-authoritative
    - composer dumpautoload -o
    - mkdir storage/logs -p

language:
  engines:
    swoole:
      command: php engineer server:start
