name: Test Framework

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string

permissions:
  contents: read

jobs:
  frameworks:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.5"
          bundler-cache: true

      - name: Install deps
        run: bundle install --jobs 4 --retry 3

      - name: Set matrix
        id: set-matrix
        run: echo "matrix=$(bundle exec rake ci:frameworks)" >> "$GITHUB_OUTPUT"
        env:
          LANGUAGE: ${{ inputs.language }}

  engines:
    needs: frameworks
    if: ${{ fromJson(needs.frameworks.outputs.matrix).framework[0] != null }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.frameworks.outputs.matrix) }}

    uses: ./.github/workflows/test-engine.yml
    with:
      language: ${{ inputs.language }}
      framework: ${{ matrix.framework }}
